### ISSUE TITLE
Extension yields errors if advisories exist

### ISSUE THREAD

**Issue by NotMyFault** [Wadeck/extension-jenkins-security#1]
Hey,

I was giving the extension a try, but it yields errors and doesn't display the banner from the readme:

![Screenshot 2024-01-21 at 16 23 16](https://github.com/Wadeck/extension-jenkins-security/assets/13383509/d1b5b6d9-4683-4b36-8e66-1d41027ac3b6)
![Screenshot 2024-01-21 at 16 22 19](https://github.com/Wadeck/extension-jenkins-security/assets/13383509/e59fabd1-0c8c-4a22-8e43-dfae1215872c)

### Setup

I am using Chrome version 120.0.6099.234 on MacOS version 14.2.1 (23C71) if that helps.
I installed the extension by loading it as described in the README, and obtained it previously via `git clone https://github.com/Wadeck/extension-jenkins-security`

**Comment by Wadeck** [comment]
@NotMyFault Try updating, it should work now :)

**Comment by NotMyFault** [comment]
> @NotMyFault Try updating, it should work now :)

![Screenshot 2024-01-22 at 21 25 43](https://github.com/Wadeck/extension-jenkins-security/assets/13383509/b30ef009-de8e-4cda-bb65-99c0250774df)

Thanks, works like a charm!

**Comment by Wadeck** [comment]
Good job disclosing it's working without disclosing for which repo :)))
